# .github/workflows/javadoc.yml
name: Publish JavaDoc

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Build project with Maven
        run: mvn clean install javadoc:javadoc

      - name: Deploy JavaDoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/apidocs
          publish_branch: gh-pages
          destination_dir: javadoc
